language: r

sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages:
  - hadley/testthat

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
